os: linux
  dist: trusty
  # VM-based builds turned out to be faster
  sudo: required
  addons:
    apt:
      sources:
        - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
          key_url: https://packages.microsoft.com/keys/microsoft.asc
      packages:
        - powershell

script:
  pwsh 'exit 1'

